### ISSUE TITLE
main.css 文件中有重复代码  .align-stretch 

### ISSUE THREAD

**Issue by Lee2011** [weilanwl/coloruicss#163]
https://github.com/weilanwl/ColorUI/blob/master/Colorui-UniApp/colorui/main.css 文件中有重复代码:

line 2848 和 line 2868 都定义了同样的样式：

```css
.align-stretch {
	align-items: stretch;
}
```

![image](https://user-images.githubusercontent.com/1279697/60412165-b7430080-9c02-11e9-9b03-26c037af174f.png)
