### ISSUE TITLE
小程序购物车商品加减组件

### ISSUE THREAD

**Issue by houguang** [weilanwl/coloruicss#206]
```css
.buy-number-change {
	width: 200rpx;
	height: 60rpx;
	display: flex;
	justify-content: center;
	align-items: center;
	border: 1px solid var(--blue);
	border-radius: 5px;
	overflow: hidden;
	position: relative;
}
.btn-less::after,.btn-less::before,.btn-plus::after,.btn-plus::before{
	display: none;
}
.btn-less,.btn-plus {
	width: 60rpx;
	border: none;
	height: 60rpx;
	line-height: 60rpx;
	border-radius: 0;
	display: block;
	position: absolute;
	padding: 0;
	text-align: center;
	background-color: var(--blue);
	color: var(--white)
}
.btn-less {
	left: 0;
}
.btn-plus{
	right: 0;
}
.buy-number-input {
	width: 3em;
	text-align: center;
	color: var(--blue);
}
```
```html
<view class="buy-number-change margin-left">
    <button class="btn-less" bindtap="goodsLess">-</button>
    <input class="buy-number-input" disabled="true" type="number" value="{{detail.count}}" />
    <button class="btn-plus" bindtap="goodsPlus">+</button>
</view>
```
![image](https://user-images.githubusercontent.com/1720347/65051664-0f84d580-d99c-11e9-91f8-2944ee51f891.png)
