### ISSUE TITLE
vue组件中引入animation.css调试报警告

### ISSUE THREAD

**Issue by gongph** [weilanwl/coloruicss#219]
报错如下：

```bash
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/college/college.wxss:18:1)This wxss file is ignored. at app-view.js:5384
```
同事代码里引入了colorui中的 animation.css 。查了一下，虽然不影响项目启动，但是这个错误确实看着不爽。

**Comment by gongph** [comment]
里面有个样式：

```css
[class*=animation-] {
    animation-duration: .5s;
    animation-timing-function: ease-out;
    animation-fill-mode: both
}
```
